on: [push]
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    cache: 'npm'
- run: git clone https://github.com/jdadonut/booru
- run: git clone https://github.com/jdadonut/booru-browser-supplements ./suppl
- run: cd booru
- run: npm install
- run: tsc
- run: webpack
- run: mv ./pack/booru.js ../suppl
- run: cd ..
- run: cd supl
- run: git commit booru.js -m "Automagic commit."
- run: git push 
