on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          
      # - run: export TOKEN=${{secrets.GITHUB_TOKEN}}
      - run: |
          cd .. &&\
          git clone https://github.com/jdadonut/booru &&\
          git clone https://github.com/jdadonut/booru-browser-supplements ./booru-suppl &&\
          cd booru &&\
          npm i &&\
          tsc &&\
          webpack &&\
          mv ./pack/booru.js ../booru-suppl &&\
          cd .. &&\
          cd booru-suppl &&\
          git branch -M main &&\
          git add booru.js &&\
          git config --local user.email "47060357+jdadonut@users.noreply.github.com" &&\
          git config --local user.name "Jai L." &&\
          git commit booru.js -m "Automagic commit." &&\
          git push "https://jdadonut:${{ secrets.PUSHKEY }}@github.com/jdadonut/booru-browser-supplements.git" HEAD:main 