on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          
      # - run: export TOKEN=${{secrets.GITHUB_TOKEN}}
      - run: |
          cd .. \
          git clone https://github.com/jdadonut/booru \
          git clone https://github.com/jdadonut/booru-browser-supplements ./suppl \
          cd booru \
          npm i \
          tsc \
          webpack \
          mv ./pack/booru.js ../suppl \
          cd .. \
          cd suppl \
          git branch -M main \
          git add booru.js \
          git config --local user.email "47060357+jdadonut@users.noreply.github.com" \
          git config --local user.name "github-actions[bot]" \
          git commit booru.js -m "Automagic commit." \
          # git remote remove origin \
          # git remote add origin https://github.com/jdadonut/booru-browser-supplements.git \
          git push "https://jdadonut:${{ secrets.}}@github.com/jdadonut/booru-browser-supplements.git" HEAD:main
  